### ISSUE TITLE
Timeout on long open connection

### ISSUE THREAD

**Issue by MCRedJay** [chitika/cberl#22]
I've had a connection open thru cberl for several days. Each day, I go in and set one document value and then retrieve it.   This was working great, until today.

Here's the error I got:
https://gist.github.com/MCRedJay/991240399ce0272451a0

Notice on line 14, I am able to set it to todays date.  But the request then times out.  I logged into the CB console and couch base is up and running fine.  I checked and the set did complete successfully.

But all further requests resulted in a timeout error. 

FWIW, closing the connection pool and then immediately starting up a new one fixed the problem. 

So my issue/question is:   If you have a long running service (e.g.: up 24/7/365) and a lot of connections in that service hitting the database, should you be opening a connection pool and running these calls thru it (so they are aggregated) and leaving it up a long time?

Or should each service do an open / get/ close cycle on every request?  

I'm guessing open and close are much heavier weight than set/get .... but if we don't do that, hard to know when we can reset the pool-- if you can't leave a pool open for months at a time. 

I suspect what happened here was a momentary (e.g.: seconds) loss of connectivity to the remote machine, causing the first time out, and then subsequent timeouts were due to things being in a bad state (possibly at the libcouchbase layer.)

**Comment by hlieberman** [comment]
I'm going to close this as unreproducable.  @MCRedJay, if you are still experiencing this problem, please let me know and we'll reopen the ticket and try to help you get it fixed.
