### ISSUE TITLE
app craches on startup when using cberl

### ISSUE THREAD

**Issue by MarkNijhof** [chitika/cberl#55]
Hi,

I am surly doing something silly, but whenever I try: cberl:start_link(cberl_default, 5) my app craches without giving me a reason (looks almost like normal init:stop)

In the deps folder in cberl I can run nearly all tests, the view tests fail but others pass just fine. There is a crashlog but that is so bit that I don't know where to look for, any hints would be appreciated!

-Mark

**Comment by hlieberman** [comment]
I'm going to close this as unreproducible.  @MarkNijhof, if you are still having this problem, please comment and we'll see what we can do to help!
