### ISSUE TITLE
etimedout error

### ISSUE THREAD

**Issue by JamieTabone** [chitika/cberl#70]
When the I am using the set method an etimedout error is being received. What is this timeout? Is there a way to increase it?

Thank you

**Comment by fauxsoup** [comment]
'etimedout' is a standard socket error and indicates that the connection to the server timed out for one of several reasons (issue with TCP keepalive, too long trying to recv, attempting to recv on a socket that's not connected, and more) . This error generally indicates an issue communicating with whatever service (in this case Couchbase) to which you're trying to connect.

You should consult your platforms documentation for information on adjusting TCP timeout values, but please note that this will probably just delay your receipt of the error message. You should debug your couchbase deployment to try and determine what is actually causing the client to time out (for example, maybe the memcached instances are not running, or perhaps a firewall is block your access to the server).

**Comment by JamieTabone** [comment]
Thank you for your time. I will look into it.
