### ISSUE TITLE
touch command cause memory leak

### ISSUE THREAD

**Issue by linbo** [chitika/cberl#73]
Hi,

For touch command, it will malloc memory for [args->exp](https://github.com/chitika/cberl/blob/master/c_src/cb.c#L380), and if failed memory will be cleanup

```
 error2:
    free(args->exp);
```
But if no error occur, this memory does not cleanup in cb_mtouch method.

Here is the [fixed code](https://github.com/yunba/cberl/commit/c39a49f07d5b6bd01439d5b3bc8c0c41ffc3e97f).

**Comment by wuyingfengsui** [comment]
Here is [the pull request](https://github.com/chitika/cberl/pull/74) from yunba

**Comment by fauxsoup** [comment]
Pull request merged.
